import assert from "node:assert/strict";
import test from "node:test";

// There is deliberately no development OTP bypass. DEV_MEMBER_OTP_BYPASS /
// DEV_MEMBER_OTP_CODE may still linger in .env files but nothing reads them; a bypass
// that defaulted to on would be a production login hole. This guards against one being
// reintroduced without a matching review of that risk.
test("no development OTP bypass is exported from the user service", async () => {
  const userService: Record<string, unknown> = await import("./user.service");
  assert.equal("getDevelopmentMemberOtpCode" in userService, false);
});

test("production OTP eligibility, provider verification, limits and sessions", {
  skip: process.env.RUN_MYSQL_INTEGRATION !== "1"
}, async t => {
  process.env.NODE_ENV="test";process.env.OTP_HASH_SECRET="unit-test-otp-hash-secret";
  const [{UserService},{OtpSecurityService},{normalizeIndianMobile},{requireAuth},{Msg91OtpService},{resolveProfileMembershipNo}]=await Promise.all([import("./user.service"),import("./otp-security.service"),import("../utils/phone"),import("../middleware/authMiddleware"),import("./msg91-otp.service"),import("../controllers/member.controller")]);
  await (await import("../config/db")).getDbPool();
  const baseMember:any={id:42,membershipNo:"BSF-OTP-42",fullName:"OTP Member",email:"otp@example.test",mobileNo:"8401829027",academyId:"swim",registration_status:"Approved",payment_status:"Paid",membership_status:"Active",login_enabled:true,membership_end_date:"2099-12-31"};
  // The provider only delivers; the code itself is generated here and verified locally
  // against the hash stored on the challenge, so tests drive it through the sent value.
  const SENT_OTP="123456";
  const build=(member:any=baseMember,providerResult:any={send:{success:true,requestId:"req-test",otp:SENT_OTP}},clockRef={value:Date.now()})=>{
    const provider={sendCalls:0,async send(){this.sendCalls++;return providerResult.send;}};
    const repository={async getByPhone(){return member;}};
    const security=new OtpSecurityService(undefined as any,()=>clockRef.value);
    return{service:new UserService({memberRepository:repository as any,otpProvider:provider as any,otpSecurity:security}),provider,clockRef,security};
  };

  await t.test("active paid approved member is allowed",async()=>{const{service,provider}=build();const result=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"1.1.1.1"});assert.equal(result.success,true);assert.equal(provider.sendCalls,1);});
  for(const [name,changes] of [["pending approval",{registration_status:"Pending"}],["approved but unpaid",{payment_status:"Pending"}],["inactive member",{membership_status:"Inactive"}],["login disabled",{login_enabled:false}],["rejected member",{registration_status:"Rejected"}],["blocked member",{blocked:true}],["deleted member",{is_deleted:true}],["expired membership",{membership_end_date:"2020-01-01"}]] as const){await t.test(`${name} is denied`,async()=>{const{service,provider}=build({...baseMember,...changes});const result=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"2.2.2.2"});assert.equal(result.success,false);assert.equal(result.code,"MEMBER_INELIGIBLE");assert.equal(provider.sendCalls,0);});}
  await t.test("correct provider-verified OTP creates member session",async()=>{const{service}=build();await service.sendOtp({phoneNumber:"+918401829027",role:"member",ipAddress:"3.3.3.3"});const result=await service.login({phoneNumber:"918401829027",role:"member",otpCode:"123456",ipAddress:"3.3.3.3"});assert.equal(result.success,true);assert.equal((await UserService.getSession(result.token!))?.userId,"usr_member_42");});
  await t.test("wrong OTP is denied",async()=>{const{service}=build();await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"4.4.4.4"});const result=await service.login({phoneNumber:"8401829027",role:"member",otpCode:"111111",ipAddress:"4.4.4.4"});assert.equal(result.code,"OTP_INVALID");assert.equal(result.success,false);});
  await t.test("expired challenge is denied even with the correct code",async()=>{const clock={value:Date.now()};const{service}=build(baseMember,undefined,clock);await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"5.5.5.5"});clock.value+=301000;const result=await service.login({phoneNumber:"8401829027",role:"member",otpCode:SENT_OTP,ipAddress:"5.5.5.5"});assert.equal(result.code,"OTP_EXPIRED");});
  await t.test("30-second resend cooldown is enforced",async()=>{const{service,provider}=build();await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"6.6.6.6"});const result=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"6.6.6.6"});assert.equal(result.code,"OTP_COOLDOWN");assert.equal(provider.sendCalls,1);});
  await t.test("rolling phone request limit is enforced",async()=>{const clock={value:Date.now()};const{service}=build(baseMember,undefined,clock);for(let i=0;i<5;i++){const result=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"7.7.7.7"});assert.equal(result.success,true);clock.value+=31000;}const limited=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"7.7.7.7"});assert.equal(limited.code,"OTP_RATE_LIMIT");});
  await t.test("verification attempts are capped",async()=>{const{service}=build();await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"8.8.8.8"});for(let i=0;i<5;i++)await service.login({phoneNumber:"8401829027",role:"member",otpCode:"111111",ipAddress:"8.8.8.8"});const limited=await service.login({phoneNumber:"8401829027",role:"member",otpCode:"111111",ipAddress:"8.8.8.8"});assert.equal(limited.code,"OTP_ATTEMPTS_EXCEEDED");});
  await t.test("Indian mobile formats normalize identically",()=>{assert.deepEqual(normalizeIndianMobile("8401829027"),normalizeIndianMobile("+91 8401829027"));assert.deepEqual(normalizeIndianMobile("918401829027"),normalizeIndianMobile("8401829027"));});
  await t.test("provider failure never returns fake success or credentials",async()=>{process.env.MSG91_AUTH_KEY="secret-never-return";process.env.MSG91_SENDER_ID="SENDER-NEVER-RETURN";const{service}=build(baseMember,{send:{success:false,reason:"provider"}});const result=await service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"9.9.9.9"});assert.equal(result.success,false);assert.equal(result.code,"OTP_PROVIDER_FAILURE");assert.doesNotMatch(JSON.stringify(result),/secret-never-return|SENDER-NEVER-RETURN/);});
  // MSG91's /api/v5/otp product answers 200 {"type":"success"} to anything - including a
  // bogus template id - and only fails asynchronously, so delivery goes through sendhttp
  // with the approved DLT header instead. Never move this back onto the OTP endpoint.
  await t.test("OTP is delivered through sendhttp with the approved DLT header",async()=>{process.env.MSG91_AUTH_KEY="test-auth-key";process.env.MSG91_SENDER_ID="BARSWF";process.env.MSG91_OTP_DLT_TEMPLATE_ID="1777179075213426676";const calls:any[]=[];const http:any={async get(...args:any[]){calls.push(args);return{data:"366a686d6c7663784c506b37"};},async post(){throw new Error("OTP must not be sent through the MSG91 OTP API");}};const provider=new Msg91OtpService(http);const sent=await provider.send("918401829027");assert.equal(sent.success,true);assert.match(String(sent.otp),/^\d{6}$/);assert.equal(calls[0][0],"https://control.msg91.com/api/sendhttp.php");const params=calls[0][1].params;assert.equal(params.authkey,"test-auth-key");assert.equal(params.sender,"BARSWF");assert.equal(params.DLT_TE_ID,"1777179075213426676");assert.equal(params.mobiles,"918401829027");assert.equal(params.message,`Your OTP for Baroda Swim Front login is ${sent.otp}. It is valid for 5 minutes. Do not share this OTP with anyone. - Baroda Swim Front`);});
  await t.test("a rejected sendhttp response is not treated as delivered",async()=>{process.env.MSG91_AUTH_KEY="test-auth-key";process.env.MSG91_SENDER_ID="BARSWF";process.env.MSG91_OTP_DLT_TEMPLATE_ID="1777179075213426676";const http:any={async get(){return{data:"ERROR: invalid template"};},async post(){throw new Error("unexpected");}};assert.equal((await new Msg91OtpService(http).send("918401829027")).success,false);});
  await t.test("unknown and ineligible accounts receive the same denial",async()=>{const missing=build(null);const pending=build({...baseMember,registration_status:"Pending"});const a=await missing.service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"10.0.0.1"});const b=await pending.service.sendOtp({phoneNumber:"8401829027",role:"member",ipAddress:"10.0.0.2"});assert.equal(a.error,b.error);});
  await t.test("member authorization rejects missing sessions and disallowed roles",async()=>{const middleware=requireAuth(["member"]);const makeRes=()=>{const state:any={};return{state,status(code:number){state.code=code;return this;},json(body:any){state.body=body;return this;}};};const missingRes:any=makeRes();await middleware({headers:{}},missingRes,()=>{});assert.equal(missingRes.state.code,401);const token=await UserService.createSession({userId:"usr_admin_1",email:"a@b.test",role:"admin",name:"Admin",academyId:"swim",expiresAt:Date.now()+60000});const wrongRoleRes:any=makeRes();await middleware({headers:{"x-session-token":token}},wrongRoleRes,()=>{});assert.equal(wrongRoleRes.state.code,403);});
  await t.test("authenticated member identity overrides another membership number",async()=>{let lookedUpId=0;const resolved=await resolveProfileMembershipNo("BSF-SOMEONE-ELSE",{role:"member",userId:"usr_member_42"},async id=>{lookedUpId=id;return"BSF-OTP-42";});assert.equal(lookedUpId,42);assert.equal(resolved,"BSF-OTP-42");});
});
