import React from "react";
import { ReceiptText } from "lucide-react";
import { formatMemberDate, type MemberPayment } from "./member-overview-data";
import { PaymentCardMobile } from "./PaymentCardMobile";
import { PaymentDocumentActions } from "./PaymentDocumentActions";
import { PaymentStatusBadge } from "./PaymentStatusBadge";
import { filterMemberPayments, presentPaymentStatus, type PaymentFilter } from "./payment-presentation";

const filters: PaymentFilter[] = ["All", "Paid", "Pending", "Failed", "Refunded"];
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export function PaymentHistory({ payments, filter, onFilterChange }: { payments: MemberPayment[]; filter: PaymentFilter; onFilterChange: (filter: PaymentFilter) => void }) {
  const visiblePayments = filterMemberPayments(payments, filter);
  return <section aria-labelledby="payment-history-title" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]">
    <div className="border-b border-slate-100 px-5 py-4 sm:flex sm:items-center sm:justify-between sm:gap-5 sm:px-6"><div><h2 id="payment-history-title" className="text-lg font-semibold text-slate-950">Payment history</h2><p className="mt-0.5 text-sm text-slate-500">Newest transactions first</p></div><div className="member-payment-filters mt-4 flex gap-1 overflow-x-auto pb-1 sm:mt-0" role="group" aria-label="Filter payments by status">{filters.map(item => <button key={item} type="button" onClick={() => onFilterChange(item)} aria-pressed={filter === item} className={`min-h-10 shrink-0 rounded-lg px-3 text-xs font-semibold transition focus:outline-none focus:ring-2 focus:ring-cyan-500 ${filter === item ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{item}</button>)}</div></div>
    {visiblePayments.length === 0 ? <div className="px-6 py-12 text-center"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-slate-50 text-slate-400"><ReceiptText className="h-5 w-5" /></span><p className="mt-3 text-sm font-semibold text-slate-800">{payments.length ? `No ${filter.toLowerCase()} payments` : "No payment history yet."}</p><p className="mt-1 text-sm text-slate-500">{payments.length ? "Try another status filter." : "Your membership payments and documents will appear here."}</p></div> : <>
      <div className="divide-y divide-slate-100 xl:hidden">{visiblePayments.map((payment, index) => <React.Fragment key={`${payment.paymentDate}-${payment.receiptNo || index}`}><PaymentCardMobile payment={payment} /></React.Fragment>)}</div>
      <div className="hidden xl:block"><table className="w-full table-fixed text-left text-sm"><thead className="bg-slate-50/80 text-xs font-medium text-slate-500"><tr><th className="w-[13%] px-6 py-3">Date</th><th className="w-[21%] px-4 py-3">Membership / plan</th><th className="w-[13%] px-4 py-3">Amount</th><th className="w-[13%] px-4 py-3">Status</th><th className="w-[20%] px-4 py-3">Receipt</th><th className="w-[20%] px-6 py-3">Invoice</th></tr></thead><tbody className="divide-y divide-slate-100">{visiblePayments.map((payment, index) => { const status = presentPaymentStatus(payment); return <tr key={`${payment.paymentDate}-${payment.receiptNo || index}`} className="align-top"><td className="whitespace-nowrap px-6 py-5 text-slate-600">{formatMemberDate(payment.paymentDate) || "Date pending"}</td><td className="px-4 py-5"><p className="truncate font-semibold text-slate-900">{payment.planName || "Membership"}</p>{payment.paymentMethod && <p className="mt-1 text-xs text-slate-500">{payment.paymentMethod}</p>}</td><td className="whitespace-nowrap px-4 py-5 font-semibold text-slate-950">{currency.format(payment.amount)}{status === "Refunded" && <p className="mt-1 text-xs font-normal text-sky-700">Refund {currency.format(Number(payment.refundAmount || 0))}</p>}</td><td className="px-4 py-5"><PaymentStatusBadge payment={payment} />{status === "Refunded" && formatMemberDate(payment.refundDate) && <p className="mt-1.5 whitespace-nowrap text-xs text-slate-500">{formatMemberDate(payment.refundDate)}</p>}</td><td className="px-4 py-5"><p className="mb-2 truncate text-xs text-slate-500">{payment.receiptNo || "No receipt number"}</p><PaymentDocumentActions payment={payment} type="receipt" compact /></td><td className="px-6 py-5"><p className="mb-2 truncate text-xs text-slate-500">{payment.invoiceNo || "No invoice number"}</p><PaymentDocumentActions payment={payment} type="invoice" compact /></td></tr>})}</tbody></table></div>
    </>}
  </section>;
}
